// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9V7A_hoqJrqFA1MFoJOobpBrCDnlo80',
    appId: '1:651583070051:web:e959a089c89ffbf961bd56',
    messagingSenderId: '651583070051',
    projectId: 'hersafezone-b6e72',
    authDomain: 'hersafezone-b6e72.firebaseapp.com',
    storageBucket: 'hersafezone-b6e72.firebasestorage.app',
    measurementId: 'G-7ZJ7H8VZVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpEboK-hPNYo9McC8I5j8axvD_1cg5aoU',
    appId: '1:651583070051:android:e8e53d3c790839f961bd56',
    messagingSenderId: '651583070051',
    projectId: 'hersafezone-b6e72',
    storageBucket: 'hersafezone-b6e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8M18uoy3BW8J_AH5Vl_3j37YRiIKJf7o',
    appId: '1:651583070051:ios:8ba1fdc9ebfb219261bd56',
    messagingSenderId: '651583070051',
    projectId: 'hersafezone-b6e72',
    storageBucket: 'hersafezone-b6e72.firebasestorage.app',
    iosBundleId: 'com.example.fieldProjectTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8M18uoy3BW8J_AH5Vl_3j37YRiIKJf7o',
    appId: '1:651583070051:ios:8ba1fdc9ebfb219261bd56',
    messagingSenderId: '651583070051',
    projectId: 'hersafezone-b6e72',
    storageBucket: 'hersafezone-b6e72.firebasestorage.app',
    iosBundleId: 'com.example.fieldProjectTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu9V7A_hoqJrqFA1MFoJOobpBrCDnlo80',
    appId: '1:651583070051:web:ebad59b475d6a96261bd56',
    messagingSenderId: '651583070051',
    projectId: 'hersafezone-b6e72',
    authDomain: 'hersafezone-b6e72.firebaseapp.com',
    storageBucket: 'hersafezone-b6e72.firebasestorage.app',
    measurementId: 'G-T2DD39CQ5V',
  );
}
